
version: 2
jobs:
  test-and-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - build
          key: react-build-cache-{{ .Environment.CIRCLE_SHA1 }}
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - restore_cache:
          keys:
          - react-build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install netlify CLI
          command: wget -qO- 'https://cli.netlify.com/download/latest/linux' | tar xz
      - run:
          name: Deploy build artifact to netlify
          command: ./netlifyctl deploy -b ./build -A $NETLIFY_ACCESS_TOKEN -y -n react-random-name-staging
          when: on_fail
      - run:
          name: cat logs
          command: cat netlifyctl-debug.log
          

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test-and-build
      - deploy:
          requires:
            - test-and-build